import {
  isFigmaColorValue,
  isFigmaVariableAlias,
  type FigmaColorValue,
  type FigmaVariable,
  type FigmaVariableCollection,
  type FigmaVariableValue,
  type FigmaVariablesPayload,
} from './types';

export type ThemeLeafValue = string | number | boolean | null;
export type ThemeValue = ThemeLeafValue | { readonly [key: string]: ThemeValue };
export type ThemeObject = Record<string, ThemeValue>;
export type ThemesObject = Record<string, ThemeObject>;
export type BreakpointsObject = Record<string, number>;

export interface TransformFigmaVariablesResult {
  themes: ThemesObject;
  breakpoints: BreakpointsObject;
  diagnostics: string[];
}

interface TransformContext {
  collectionsById: Map<string, FigmaVariableCollection>;
  variablesById: Map<string, FigmaVariable>;
  diagnostics: string[];
}

const COLLECTION_NAMESPACE_ALIASES: Record<string, string> = {
  color: 'colors',
  colors: 'colors',
  colour: 'colors',
  colours: 'colors',
  spacing: 'spacing',
  space: 'spacing',
  radius: 'radius',
  radii: 'radius',
  typography: 'typography',
  font: 'typography',
  fonts: 'typography',
  opacity: 'opacity',
  zindex: 'zIndex',
  zindices: 'zIndex',
  breakpoint: 'breakpoints',
  breakpoints: 'breakpoints',
};

const RESERVED_THEME_NAMES: Record<string, string> = {
  light: 'light',
  jasny: 'light',
  dark: 'dark',
  ciemny: 'dark',
};

export const transformFigmaVariables = (payload: FigmaVariablesPayload): TransformFigmaVariablesResult => {
  const collections = Object.values(payload.variableCollections);
  const variables = Object.values(payload.variables).filter((variable) => !variable.hiddenFromPublishing);
  const context: TransformContext = {
    collectionsById: new Map(collections.map((collection) => [collection.id, collection])),
    variablesById: new Map(variables.map((variable) => [variable.id, variable])),
    diagnostics: [],
  };

  const themeNames = collectThemeNames(collections);
  const themes = Object.fromEntries(themeNames.map((themeName) => [themeName, {} as ThemeObject]));
  const breakpoints: BreakpointsObject = {};

  for (const variable of variables) {
    const collection = context.collectionsById.get(variable.variableCollectionId);

    if (!collection || collection.hiddenFromPublishing) {
      continue;
    }

    const namespace = normalizeCollectionName(collection.name);
    const path = splitTokenPath(variable.name);

    if (path.length === 0) {
      context.diagnostics.push(`Skipped variable with empty path: ${variable.id}`);
      continue;
    }

    if (namespace === 'breakpoints') {
      const value = resolveVariableForTheme(variable, themeNames[0] ?? 'light', context);
      const breakpointName = path.at(-1);

      if (typeof value === 'number' && breakpointName) {
        breakpoints[breakpointName] = value;
      } else {
        context.diagnostics.push(`Skipped non-numeric breakpoint "${variable.name}".`);
      }

      continue;
    }

    for (const themeName of themeNames) {
      const value = resolveVariableForTheme(variable, themeName, context);

      if (value === undefined) {
        continue;
      }

      const theme = themes[themeName];

      if (!theme) {
        continue;
      }

      const convertedValue = convertVariableValue(value);

      if (convertedValue === undefined) {
        context.diagnostics.push(`Skipped unsupported value for "${variable.name}" in theme "${themeName}".`);
        continue;
      }

      const namespaceObject = ensureObject(theme, namespace);
      setDeepValue(namespaceObject, path, convertedValue);
    }
  }

  if (Object.keys(breakpoints).length === 0) {
    breakpoints.xs = 0;
    context.diagnostics.push('No breakpoint variables were found; generated a default xs: 0 breakpoint.');
  }

  return {
    themes,
    breakpoints,
    diagnostics: context.diagnostics,
  };
};

export const createGeneratedThemesSource = ({ themes, breakpoints, diagnostics }: TransformFigmaVariablesResult): string => {
  const header = [
    '/* eslint-disable */',
    '// This file is generated by scripts/generate-tokens.ts.',
    '// Do not edit it manually.',
    '',
  ];

  const diagnosticsComment =
    diagnostics.length > 0
      ? [
          '/**',
          ' * Generator diagnostics:',
          ...diagnostics.map((diagnostic) => ` * - ${diagnostic}`),
          ' */',
          '',
        ]
      : [];

  return `${[...header, ...diagnosticsComment].join('\n')}export const breakpoints = ${stringifyAsConst(
    breakpoints,
  )};\n\nexport const themes = ${stringifyAsConst(
    themes,
  )};\n\nexport type VaveBreakpoints = typeof breakpoints;\nexport type VaveThemeName = keyof typeof themes;\nexport type VaveTheme = (typeof themes)[VaveThemeName];\n`;
};

export const createGeneratedTypesSource = (): string =>
  [
    '/* eslint-disable */',
    '// This file is generated by scripts/generate-tokens.ts.',
    '// Do not edit it manually.',
    '',
    "export type { VaveBreakpoints, VaveTheme, VaveThemeName } from './themes';",
    "export type { FontAssetFileName, FontAssetName } from './fonts';",
    "export type { IconName, IconSize, IconVariant, IconWeight, IconWeightFor } from './icons';",
    "export type { FontFamilyName, TypographyName, TypographyStyle } from './typography';",
    '',
  ].join('\n');

const collectThemeNames = (collections: FigmaVariableCollection[]): string[] => {
  const names = new Set<string>();

  for (const collection of collections) {
    for (const mode of collection.modes) {
      names.add(normalizeThemeName(mode.name));
    }
  }

  const hasLight = names.has('light');
  const hasDark = names.has('dark');

  if (hasLight && hasDark) {
    return ['light', 'dark'];
  }

  return names.size > 0 ? [...names].sort() : ['light'];
};

const resolveVariableForTheme = (
  variable: FigmaVariable,
  themeName: string,
  context: TransformContext,
  seen = new Set<string>(),
): FigmaVariableValue | undefined => {
  const cycleKey = `${variable.id}:${themeName}`;

  if (seen.has(cycleKey)) {
    context.diagnostics.push(`Detected alias cycle while resolving "${variable.name}" for theme "${themeName}".`);
    return undefined;
  }

  seen.add(cycleKey);

  const collection = context.collectionsById.get(variable.variableCollectionId);

  if (!collection) {
    context.diagnostics.push(`Missing collection for variable "${variable.name}".`);
    return undefined;
  }

  const mode = findModeForTheme(collection, themeName);
  const rawValue = variable.valuesByMode[mode.modeId] ?? variable.valuesByMode[collection.defaultModeId];

  if (rawValue === undefined) {
    context.diagnostics.push(`Missing value for "${variable.name}" in theme "${themeName}".`);
    return undefined;
  }

  if (!isFigmaVariableAlias(rawValue)) {
    return rawValue;
  }

  const target = context.variablesById.get(rawValue.id);

  if (!target) {
    context.diagnostics.push(`Missing alias target "${rawValue.id}" for variable "${variable.name}".`);
    return undefined;
  }

  return resolveVariableForTheme(target, themeName, context, seen);
};

const findModeForTheme = (collection: FigmaVariableCollection, themeName: string) => {
  const exactMode = collection.modes.find((mode) => normalizeThemeName(mode.name) === themeName);
  const defaultMode = collection.modes.find((mode) => mode.modeId === collection.defaultModeId);

  return exactMode ?? defaultMode ?? collection.modes[0]!;
};

const convertVariableValue = (value: FigmaVariableValue): ThemeLeafValue | undefined => {
  if (isFigmaColorValue(value)) {
    return figmaColorToCss(value);
  }

  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === null) {
    return value;
  }

  return undefined;
};

export const figmaColorToCss = ({ r, g, b, a }: FigmaColorValue): string => {
  const red = colorChannelToHex(r);
  const green = colorChannelToHex(g);
  const blue = colorChannelToHex(b);
  const alpha = clamp(a, 0, 1);

  if (alpha >= 1) {
    return `#${red}${green}${blue}`;
  }

  const rgbaAlpha = Number(alpha.toFixed(3));

  return `rgba(${colorChannelToInt(r)}, ${colorChannelToInt(g)}, ${colorChannelToInt(b)}, ${rgbaAlpha})`;
};

const colorChannelToInt = (value: number): number => Math.round(clamp(value, 0, 1) * 255);

const colorChannelToHex = (value: number): string => colorChannelToInt(value).toString(16).padStart(2, '0');

const clamp = (value: number, min: number, max: number): number => Math.min(Math.max(value, min), max);

const normalizeThemeName = (name: string): string => {
  const normalized = toCamelCase(name);

  return RESERVED_THEME_NAMES[normalized.toLowerCase()] ?? normalized;
};

const normalizeCollectionName = (name: string): string => {
  const normalized = toCamelCase(name);

  return COLLECTION_NAMESPACE_ALIASES[normalized.toLowerCase()] ?? normalized;
};

const splitTokenPath = (name: string): string[] =>
  name
    .split(/[/.]/)
    .map((segment) => toCamelCase(segment.trim()))
    .filter(Boolean);

const toCamelCase = (value: string): string => {
  const words = value
    .replace(/['"]/g, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  if (words.length === 0) {
    return '';
  }

  const firstWord = words[0];

  if (!firstWord) {
    return '';
  }

  const restWords = words.slice(1);
  const first = startsWithNumber(firstWord) ? `_${firstWord}` : firstWord.toLowerCase();

  return [
    first,
    ...restWords.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`),
  ].join('');
};

const startsWithNumber = (value: string): boolean => /^\d/.test(value);

const ensureObject = (target: ThemeObject, key: string): ThemeObject => {
  const current = target[key];

  if (current && typeof current === 'object') {
    return current as ThemeObject;
  }

  const next: ThemeObject = {};
  target[key] = next;

  return next;
};

const setDeepValue = (target: Record<string, unknown>, path: string[], value: unknown): void => {
  let current = target;

  for (const segment of path.slice(0, -1)) {
    const child = current[segment];

    if (child && typeof child === 'object' && !Array.isArray(child)) {
      current = child as Record<string, unknown>;
      continue;
    }

    const next: Record<string, unknown> = {};
    current[segment] = next;
    current = next;
  }

  const leaf = path.at(-1);

  if (leaf) {
    current[leaf] = value;
  }
};

const stringifyAsConst = (value: unknown): string => `${JSON.stringify(value, null, 2)} as const`;
