import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface IncomingIconAsset {
  name: string;
  weight: string;
  size: number;
  sizes: number[];
  weights: string[];
  svg: string;
  sourceNodeId: string;
}

interface IncomingPayload {
  icons: IncomingIconAsset[];
}

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = resolve(projectRoot, 'tokens/figma.icon-assets.json');

const main = async (): Promise<void> => {
  const payload = JSON.parse(await readFile(inputPath, 'utf8')) as IncomingPayload;

  if (!Array.isArray(payload.icons) || payload.icons.length === 0) {
    throw new Error(`Invalid icon asset payload at ${inputPath}. Expected a non-empty icons array.`);
  }

  await writeIconAssets(payload.icons);
  console.info(`[vave-styling] Imported ${payload.icons.length} icon SVG assets.`);
};

const writeIconAssets = async (icons: IncomingIconAsset[]): Promise<void> => {
  const sortedIcons = [...icons].sort((a, b) => `${a.name}:${a.weight}:${a.size}`.localeCompare(`${b.name}:${b.weight}:${b.size}`));
  const svgEntries: string[] = [];

  for (const icon of sortedIcons) {
    const iconPath = getIconPath(icon.name, icon.weight, icon.size);
    const outputPath = resolve(projectRoot, 'assets/icons', iconPath);

    await writeTextFile(outputPath, icon.svg);
    svgEntries.push(`  ${JSON.stringify(`${icon.name}:${icon.weight}:${icon.size}`)}: ${JSON.stringify(icon.svg)},`);
  }

  await writeTextFile(resolve(projectRoot, 'src/icons/svg-sources.ts'), createSvgSourcesSource(svgEntries));
  await writeTextFile(resolve(projectRoot, 'src/icons/VaveIcon.ts'), createVaveIconSource());
  await writeTextFile(resolve(projectRoot, 'src/icons/index.ts'), createIconIndexSource());
};

const writeTextFile = async (path: string, content: string): Promise<void> => {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
};

const getIconPath = (name: string, weight: string, size: number): string => `${name}/${weight}/${size}.svg`;

const createSvgSourcesSource = (entries: string[]): string =>
  [
    '/* eslint-disable */',
    '// This file is generated by scripts/import-icon-assets.ts.',
    '// Do not edit it manually.',
    '',
    'export const iconSvgSources = {',
    ...entries,
    '} as const;',
    '',
    'export type IconSvgSourceKey = keyof typeof iconSvgSources;',
    '',
  ].join('\n');

const createVaveIconSource = (): string =>
  [
    "import { createElement } from 'react';",
    "import { SvgXml } from 'react-native-svg';",
    '',
    "import { iconSizes, icons, type IconName, type IconSize, type IconWeightFor } from '../generated/icons';",
    "import { iconSvgSources } from './svg-sources';",
    '',
    'export interface VaveIconProps<TName extends IconName = IconName> {',
    '  name: TName;',
    '  size?: IconSize;',
    '  weight?: IconWeightFor<TName>;',
    '  color?: string;',
    '  testID?: string;',
    '}',
    '',
    'export const VaveIcon = <TName extends IconName>({',
    '  name,',
    '  size = 24,',
    '  weight,',
    '  color,',
    '  testID,',
    '}: VaveIconProps<TName>) => {',
    '  const icon = icons[name];',
    '  const resolvedWeight = weight ?? icon.weights[0];',
    '  const key = `${String(name)}:${String(resolvedWeight)}:${String(size)}` as keyof typeof iconSvgSources;',
    '  const xml = iconSvgSources[key];',
    '',
    '  if (!iconSizes.includes(size) || !xml) {',
    '    return null;',
    '  }',
    '',
    '  return createElement(SvgXml, {',
    '    xml: applyIconColor(xml, color),',
    '    width: size,',
    '    height: size,',
    '    ...(testID ? { testID } : {}),',
    '  });',
    '};',
    '',
    'const applyIconColor = (xml: string, color?: string): string => {',
    '  if (!color) {',
    '    return xml;',
    '  }',
    '',
    '  return xml.replace(/fill="(?!none)[^"]+"/g, `fill="${color}"`);',
    '};',
    '',
  ].join('\n');

const createIconIndexSource = (): string =>
  [
    "export { VaveIcon } from './VaveIcon';",
    "export type { VaveIconProps } from './VaveIcon';",
    "export { iconSvgSources } from './svg-sources';",
    "export type { IconSvgSourceKey } from './svg-sources';",
    '',
  ].join('\n');

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
